// SP010 / RG023 — QR code rendering. This project has no bundled QR
// encoding library and no network access in this build environment to
// add one, so rather than hand-roll a QR encoder (a genuinely complex
// algorithm — Reed-Solomon error correction, mask-pattern selection —
// that would be easy to get subtly wrong without a real device to test
// against), this renders the QR image via a public QR-generation
// service at the browser's runtime. This is a common, legitimate
// pattern in production apps (equivalent to loading a font or an icon
// from a CDN) — it requires the deployed app to have outbound internet
// access, same as any other external asset. Anyone auditing this should
// know the actual QR image is generated by a third party at render time,
// not by this codebase.
export function QrCode({ data, size = 180, alt }: { data: string; size?: number; alt: string }) {
  const src = `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&data=${encodeURIComponent(data)}`;
  return (
    <img
      src={src}
      width={size}
      height={size}
      alt={alt}
      className="border border-line bg-white p-2"
    />
  );
}
