// One navigation list for every trainer-portal page (it used to be pasted,
// slightly differently, into fifteen files).
export const trainerLinks = [
  { to: "/trainer/dashboard", label: "Dashboard" },
  { to: "/trainer/courses", label: "My Courses" },
  { to: "/trainer/roster", label: "Student Roster" },
  { to: "/trainer/lesson-builder", label: "Lesson Builder" },
  { to: "/trainer/quiz-builder", label: "Quiz Builder" },
  { to: "/trainer/live", label: "Live Teaching" },
  { to: "/trainer/content", label: "Assignments" },
  { to: "/trainer/assignments", label: "Assignments v2" },
  { to: "/trainer/lms-tools", label: "LMS Tools & Gradebook" },
  { to: "/trainer/gradebook", label: "Gradebook" },
  { to: "/trainer/attendance", label: "Attendance" },
  { to: "/trainer/analytics", label: "Cohort Analytics" },
  { to: "/trainer/communication", label: "Messages & Office Hours" },
  { to: "/trainer/evidence", label: "Evidence Review" },
  { to: "/trainer/rubrics", label: "Rubric Builder" },
  { to: "/trainer/practical-checklist", label: "Practical Checklist" },
  { to: "/trainer/simulation-review", label: "Simulation Lab Review" },
  { to: "/trainer/viva-review", label: "AI Viva Review" },
  { to: "/trainer/forums", label: "Discussion Forums" },
  { to: "/trainer/at-risk", label: "At-Risk Students" },
  { to: "/trainer/virtual-lab", label: "Virtual Business Lab" },
  { to: "/trainer/ai-assistant", label: "AI Assistant" },
  { to: "/trainer/cpd", label: "CPD Tracker" },
  { to: "/trainer/performance", label: "Performance Profile" },
];
